import { Dimensions } from 'react-native';
import { ScaledSheet } from 'react-native-size-matters';

const width =
  Dimensions.get('window').width >= Dimensions.get('window').height
    ? Dimensions.get('window').height
    : Dimensions.get('window').width;

const styles = (direction: string) =>
  ScaledSheet.create({
    container: {
      width: '100%',
      height: '100%',
      backgroundColor: '#EBEEF0',
    },
    safeAreaView: { alignSelf: 'stretch' },
    gradientTextContainer: {
      width: '126@s',
      justifyContent: 'center',
      alignItems: 'center',
      height: '22@s',
    },
    gradientTextStyle: {
      fontSize: '16@s',
      fontFamily: 'Nunito-Regular',
      fontWeight: '700',
      textAlign: 'center',
    },
    topContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      width: 38,
      marginLeft: '20@s',
    },
    container1: {
      marginTop: 20,
      paddingHorizontal: '20@s',
      width: '100%',
      height: '100%',
      paddingBottom: 25,
    },
    container2: {
      // backgroundColor: '#EBEEF0',
      width: '100%',
      height: '132@ms',
      // borderRadius: 14,s
      marginBottom: 30,
      // paddingHorizontal: '25@s',
      // paddingVertical: '25@s',
    },
    container21: {
      // backgroundColor: '#EBEEF0',
      width: '100%',
      height: '147@ms',
      // borderRadius: 14,s
      marginBottom: 30,
      // paddingHorizontal: '25@s',
      // paddingVertical: '25@s',
    },
    container22: {
      // backgroundColor: '#EBEEF0',
      width: '100%',
      height: '142@ms',
      // borderRadius: 14,s
      marginTop: 30,
      // paddingHorizontal: '25@s',
      // paddingVertical: '25@s',
    },
    profileImgContainer: {
      height: '50@s',
      width: '50@s',
      // borderRadius: '100@s',
      // borderWidth: 3,
      alignItems: 'center',
      marginTop: 20,
      justifyContent: 'center',
      marginLeft: 30,
      // marginTop: 20,
      // alignSelf: 'center',
      // justifyContent: 'center',
      borderColor: '#FECE32',
    },
    profileImgContainer1: {
      height: '40@s',
      width: '40@s',
      // borderRadius: '100@s',
      // borderWidth: 3,
      alignItems: 'center',
      marginTop: 20,
      justifyContent: 'center',
      marginLeft: 30,
      // marginTop: 20,
      // alignSelf: 'center',
      // justifyContent: 'center',
      borderColor: '#FECE32',
    },
    profileImg: {
      height: '100%',
      width: '100%',
      resizeMode: 'contain',
    },
    profileImg1: {
      height: '100%',
      width: '100%',
      resizeMode: 'contain',
    },

    inputTextContainer: {
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    profileImgCamera: {
      height: '30@s',
      width: '30@s',
      borderRadius: '30@s',
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: 'white',
      alignItems: 'center',
      justifyContent: 'center',
    },
    inputTextContainer1: {
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 40,
    },
    coinContainer2: {
      height: '19@s',
      borderRadius: 50,
      marginTop: 7,
      flexDirection: 'row',
      backgroundColor: '#EBEEF0',
    },
    rightComponent: {
      flexDirection: direction === 'rtl' ? 'row-reverse' : 'row',
      left: direction === 'rtl' ? '20@s' : undefined,
      right: direction === 'rtl' ? undefined : '20@s',
      position: 'absolute',
    },
    container3: {
      backgroundColor: '#EBEEF0',
      width: '100%',
      height: '132@ms',
      borderRadius: 14,
    },

    container31: {
      backgroundColor: '#EBEEF0',
      width: '100%',
      height: '147@ms',
      borderRadius: 14,
    },

    Container4: {
      // marginRight: 20,
    },
    Container41: {
      marginTop: 20,
      // marginRight: 20,
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    row2: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    imageContainer: {
      width: '40@s',
      height: '25@s',
      flexDirection: 'row',
      marginLeft: '21@s',
      marginTop: 8,
    },
    interestIcon1: {
      height: '25@s',
      width: '25@s',
      borderRadius: '25@s',
    },
    interestIcons: {
      height: '25@s',
      width: '25@s',
      borderRadius: '25@s',
      marginLeft: '-9@s',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    imageRound: { width: '100%', height: '100%', resizeMode: 'cover' },

    row1: {
      flexDirection: 'row',
      marginTop: 14,
      marginLeft: 23,
    },
    plusFour: {
      position: 'absolute',
      alignSelf: 'center',
      marginTop: 4,
      color: 'white',
    },
    row11: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    text1: {
      color: '#455157',
      fontSize: '14@s',
      fontWeight: '700',
      fontFamily: 'Nunito-Regular',
      height: '19@s',
      width: '88@s',
      marginTop: 28,
    },
    text11: {
      color: '#3B3B48',
      fontSize: '14@s',
      fontWeight: ' 600',
      fontFamily: 'Nunito-Regular',
      height: '19@s',
      width: '100%',
      marginTop: 15,
      marginLeft: 20,
    },
    text2: {
      color: '#455157',
      fontSize: '12@s',
      fontWeight: ' 600',
      fontFamily: 'Nunito-Regular',
      height: '16@s',
      width: '100%',
      marginTop: 4,
    },
    text22: {
      color: '#758DAC',
      fontSize: '12@s',
      fontWeight: ' 600',
      fontFamily: 'Nunito-Regular',
      height: '16@s',
      width: '100%',
      marginTop: 4,
      marginLeft: 20,
    },
    text3: {
      color: '#FB595D',
      fontSize: '12@s',
      fontWeight: ' 700',
      fontFamily: 'Nunito-Regular',
      height: '16@s',
      width: '100%',
      marginTop: 20,
      marginRight: 30,
    },
    text33: {
      color: '#FB595D',
      fontSize: '12@s',
      fontWeight: ' 700',
      fontFamily: 'Nunito-Regular',
      height: '16@s',
      width: '100%',
      marginRight: 30,
    },

    smallContainer: {
      position: 'absolute',
      justifyContent: 'space-between',
      width: '60@s',
      height: '28@s',
    },
    coinContainer222: {
      width: '100%',
      height: '28@ms',
      borderRadius: 50,
      justifyContent: 'space-around',
      alignItems: 'center',
      paddingHorizontal: '12@ms',
      flexDirection: 'row',
      backgroundColor: '#EBEEF0',
    },
    coinImage: {
      height: '18@ms',
      width: '18@ms',
      marginTop: 2,
    },
    coinText: {
      fontFamily: 'Nunito-Regular',
      fontSize: '14@s',
      fontWeight: '600',
      color: '#758DAC',
      marginTop: 2,
    },
    smallText: {
      fontFamily: 'Nunito-Regular',
      fontSize: '12@s',
      fontWeight: '600',
      color: '#84BD47',
      height: '16@s',
      width: '100%',
    },
    smallText1: {
      fontFamily: 'Nunito-Regular',
      fontSize: '14@s',
      fontWeight: '600',
      color: '#323A3D',
      marginTop: 20,
      marginLeft: 20,
      height: '19@s',
      width: '58@s',
    },
    smallText11: {
      fontFamily: 'Nunito-Regular',
      fontSize: '14@s',
      fontWeight: '600',
      color: '#323A3D',
      marginTop: 20,
      height: '19@s',
      width: '126@s',
      marginRight: 29,
    },
  });

export default styles;
