// loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';
export const CHANGE_ROUTE_NAME = 'CHANGE_ROUTE_NAME';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESPONSE = 'REGISTER_RESPONSE';
export const REGISTER_LOADING_ENDED = 'REGISTER_LOADING_ENDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';

// otp request
export const OTP_REQUEST = 'OTP_REQUEST';
export const OTP_REQUEST_RESPONSE = 'OTP_REQUEST_RESPONSE';
export const OTP_REQUEST_LOADING_ENDED = 'OTP_REQUEST_LOADING_ENDED';
export const OTP_REQUEST_FAILED = 'OTP_REQUEST_FAILED';

// otp verify
export const OTP_VERIFY = 'OTP_VERIFY';
export const OTP_VERIFY_RESPONSE = 'OTP_VERIFY_RESPONSE';
export const OTP_VERIFY_LOADING_ENDED = 'OTP_VERIFY_LOADING_ENDED';
export const OTP_VERIFY_FAILED = 'OTP_VERIFY_FAILED';

// current customer
export const SET_SELECTED_ROLE = 'SET_SELECTED_ROLE';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_MOBILE_NO = 'SET_MOBILE_NO';
export const SET_EMAIL_VERIFIED = 'SET_EMAIL_VERIFIED';
export const SET_MOBILE_VERIFIED = 'SET_MOBILE_VERIFIED';

//reset password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

//cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
