import { Dimensions } from 'react-native';
import { ScaledSheet } from 'react-native-size-matters';

const width =
  Dimensions.get('window').width >= Dimensions.get('window').height
    ? Dimensions.get('window').height
    : Dimensions.get('window').width;

const styles = (direction: string) =>
  ScaledSheet.create({
    container: {
      width: '100%',
      height: '100%',
      backgroundColor: '#EBEEF0',
    },
    // rectangle: {
    //   width: '100%',
    //   height: '110@s',
    //   backgroundColor: '#EBEEF0',
    //   paddingBottom: 25,
    // },
    safeAreaView: { alignSelf: 'stretch' },
    // container1: {
    //   backgroundColor: '#EBEEF0',
    //   // flexDirection: 'row',
    //   // justifyContent: 'center',
    //   // alignItems: 'center',
    //   width: '100%',
    //   height: '110@s',
    //   borderBottomEndRadius: 25,
    //   borderBottomStartRadius: 25,
    //   marginBottom: 40,
    //   shadowColor: '#5E5E5E',
    //   shadowOpacity: 1,
    //   shadowOffset: { width: 6, height: 10 },
    //   textShadowRadius: 6,
    //   elevation: 8,
    // },
    // topContainer: {
    //   flexDirection: 'row',
    //   // justifyContent: 'space-between',
    //   alignItems: 'center',
    //   // width: '100%',
    //   width: '38@s',
    //   marginTop: 40,
    //   // marginBottom: 32,
    //   marginLeft: 20,
    // },
    container2: {
      paddingHorizontal: '30@s',
      width: '100%',
      height: '100%',
      paddingBottom: 25,
    },
    gradientTextContainer: {
      width: '126@s',
      justifyContent: 'center',
      alignItems: 'center',
      height: '22@s',
      // marginBottom: 38,
      // marginTop: 50,
      // marginRight: 124,
      marginLeft: 67,
    },
    gradientTextStyle: {
      fontSize: '16@s',
      fontFamily: 'Nunito-Regular',
      fontWeight: '700',
      textAlign: 'center',
      width: '126@s',
      // marginLeft: 67,
    },
    inputTextContainer: {
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    inputTextContainer1: {
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 40,
    },
    rightComponent: {
      flexDirection: direction === 'rtl' ? 'row-reverse' : 'row',
      left: direction === 'rtl' ? '20@s' : undefined,
      right: direction === 'rtl' ? undefined : '20@s',
      position: 'absolute',
    },
    container3: {
      backgroundColor: '#EBEEF0',
      width: '100%',
      height: '210@s',
      borderRadius: 14,
      marginRight: 30,
    },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 30,
      height: '22@s',
    },
    row1: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 18,
      height: '22@s',
    },
    row2: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 36,
      height: '22@s',
    },
    text1: {
      color: '#455157',
      fontSize: '16@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      marginLeft: 25,
    },
    text2: {
      color: '#455157',
      fontSize: '16@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      marginRight: 25,
    },
    text3: {
      color: '#03A0E3',
      fontSize: '16@s',
      fontWeight: '700',
      fontFamily: 'Nunito-Regular',
      marginLeft: 25,
    },
    text4: {
      color: '#03A0E3',
      fontSize: '16@s',
      fontWeight: '700',
      fontFamily: 'Nunito-Regular',
      marginRight: 25,
    },
    container1: {
      // paddingHorizontal: 30,
      // marginTop: 2,
      width: '100%',
      height: '40%',
      backgroundColor: '758DAC',
      paddingBottom: 25,
    },
    topContainer: {
      // width: 38,
      height: 10,
      // left: 20,
      // radius: 50,
      // bottom: 2,
      // flexDirection: 'row',
      // justifyContent: 'center',
      // alignItems: 'center',
      // width: '100%',
      width: '38@s',
      // marginTop: 40,
      //   // marginBottom: 32,
      marginLeft: 20,
    },
    text: {
      textAlign: 'center',
      fontSize: '16@s',
      fontFamily: 'Nunito-Regular',
      fontWeight: '700',
      width: '100%',
      // marginLeft: 67,
    },
    rectangle: {
      justifyContent: 'center',
      backgroundColor: '#EBEEF0',
      width: '100%',
      height: '110@s',
      borderBottomEndRadius: 25,
      borderBottomStartRadius: 25,
      marginBottom: 40,
      shadowColor: '#5E5E5E',
      shadowOpacity: 1,
      shadowOffset: { width: 6, height: 10 },
      textShadowRadius: 6,
      elevation: 8,
    },
  });

export default styles;
