import { Dimensions } from 'react-native';
import { ScaledSheet } from 'react-native-size-matters';

const width =
  Dimensions.get('window').width >= Dimensions.get('window').height
    ? Dimensions.get('window').height
    : Dimensions.get('window').width;

const styles = (direction: string) =>
  ScaledSheet.create({
    container: {
      width: '100%',
      height: '100%',
      backgroundColor: '#EBEEF0',
    },
    safeAreaView: { alignSelf: 'stretch' },
    gradientTextContainer: {
      width: '126@s',
      justifyContent: 'center',
      alignItems: 'center',
      height: '22@s',
    },
    gradientTextStyle: {
      fontSize: '16@s',
      fontFamily: 'Nunito-Regular',
      fontWeight: '700',
      textAlign: 'center',
    },
    topContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      width: 38,
      marginLeft: '20@s',
    },
    container1: {
      // marginTop: 20,
      paddingHorizontal: '20@s',
      width: '100%',
      height: '100%',
      paddingBottom: 25,
    },
    container2: {
      width: '100%',
      height: '212@s',
      // paddingHorizontal: '25@s',
      // marginTop: 20,
    },
    container21: {
      // backgroundColor: '#EBEEF0',
      width: '100%',
      height: '132@ms',
      // borderRadius: 14,s
      marginBottom: 30,
      // paddingHorizontal: '25@s',
      // paddingVertical: '25@s',
    },
    container22: {
      // backgroundColor: '#EBEEF0',
      width: '100%',
      height: '142@ms',
      // borderRadius: 14,s
      marginTop: 30,
      // paddingHorizontal: '25@s',
      // paddingVertical: '25@s',
    },
    profileImgContainer: {
      height: '50@s',
      width: '50@s',
      // borderRadius: '100@s',
      // borderWidth: 3,
      alignItems: 'center',
      marginTop: 20,
      justifyContent: 'center',
      marginLeft: 30,
      // marginTop: 20,
      // alignSelf: 'center',
      // justifyContent: 'center',
      borderColor: '#FECE32',
    },
    profileImgContainer1: {
      width: '100%',
      marginTop: '12@s',
      paddingHorizontal: '12@s',
      alignItems: 'center',
      justifyContent: 'center',
    },
    profileImgContainer0: {
      height: '102@s',
      width: '102@s',
      alignItems: 'center',
      marginTop: 40,
      justifyContent: 'center',
      borderColor: '#FECE32',
    },
    profileImgContainer2: {
      height: '41@s',
      width: '41@s',
      alignItems: 'center',
      marginTop: '15@s',
      justifyContent: 'center',
      borderColor: '#FECE32',
    },
    profileImg: {
      height: '100%',
      width: '100%',
      resizeMode: 'contain',
    },
    profileImg0: {
      height: '100%',
      width: '100%',
      resizeMode: 'contain',
    },
    profileImg3: {
      height: '100%',
      width: '100%',
      resizeMode: 'contain',
    },
    profileImg1: {
      height: '114@s',
      width: '100%',
      resizeMode: 'stretch',
    },
    profileImg2: {
      height: 50,
      width: 34.28,
      resizeMode: 'contain',
      position: 'absolute',
    },

    inputTextContainer: {
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    profileImgCamera: {
      height: '30@s',
      width: '30@s',
      borderRadius: '30@s',
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: 'white',
      alignItems: 'center',
      justifyContent: 'center',
    },
    inputTextContainer1: {
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 40,
    },
    coinContainer2: {
      width: '100%',
      height: '100%',
      borderRadius: 50,
      // alignItems: 'center',
      flexDirection: 'row',
      backgroundColor: '#EBEEF0',
      marginLeft: 58,
      // marginTop: 3,
    },
    rightComponent: {
      flexDirection: direction === 'rtl' ? 'row-reverse' : 'row',
      left: direction === 'rtl' ? '20@s' : undefined,
      right: direction === 'rtl' ? undefined : '20@s',
      position: 'absolute',
    },
    container3: {
      backgroundColor: '#EBEEF0',
      width: '212@ms',
      height: '212@ms',
      borderRadius: 14,
      // paddingHorizontal: '30@s',
      // paddingVertical: '20@s',
    },

    container31: {
      backgroundColor: '#EBEEF0',
      width: '100%',
      height: '212@ms',
      borderRadius: 14,
      // paddingHorizontal: '30@s',
      // paddingVertical: '20@s',
    },

    Container4: {
      // marginTop: 20,
      // marginRight: 20,
    },
    container5: {
      marginTop: 20,
      // marginRight: 20,
    },
    Container41: {
      // marginTop: 20,
      // marginRight: 20,
    },
    row: {
      flexDirection: 'row',
      // justifyContent: 'space-between',
      // height: '22@s',
      marginBottom: 30,
      marginLeft: 17,
    },
    row1: {
      flexDirection: 'row',
      // justifyContent: 'space-between',
      // height: '22@s',
      marginBottom: 30,
      marginLeft: 13,
    },
    row2: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      // height: '22@s',
      // marginBottom: 18,
    },
    interestIconContainer: {
      justifyContent: 'space-between',
      backgroundColor: '#EBEEF0',
      flexDirection: 'row',
      marginVertical: '17@s',
    },
    interestIconMainContainer: {
      flexDirection: 'row',
      height: '30@s',
    },
    interestIcon1: {
      height: '25@s',
      width: '25@s',
      borderRadius: '25@s',
    },
    interestIcons: {
      height: '25@s',
      width: '25@s',
      borderRadius: '25@s',
      marginLeft: '-9@s',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    plusFourImage: {
      position: 'absolute',
      alignSelf: 'center',
    },
    imageRound: { width: '100%', height: '100%', resizeMode: 'cover' },

    row11: {
      flexDirection: 'row',
      // justifyContent: 'space-between',
      // marginBottom: 20,
      // marginTop: 14,
      // height: '22@s',
      // marginLeft: 23,
    },
    row3: {
      flexDirection: 'row',
      // justifyContent: 'space-between',
      // height: '22@s',
      marginTop: 6,
    },
    text1: {
      color: '#3B3B48',
      fontSize: '16@s',
      fontWeight: ' 600',
      fontFamily: 'Nunito-Regular',
      height: '22@s',
      width: '100%',
      marginTop: '40@s',
      // marginLeft: '35@s',
      lineHeight: 22,
      marginLeft: 35,
      // marginRight: '78@s',
      // alignItems: 'center',
      // justifyContent: 'center',
    },
    text11: {
      color: '#3B3B48',
      fontSize: '14@s',
      fontWeight: ' 600',
      fontFamily: 'Nunito-Regular',
      height: '19@s',
      width: '100%',
      marginTop: '15@s',
      marginLeft: '15@s',
      lineHeight: 22,
      // marginRight: '78@s',
      // alignItems: 'center',
      // justifyContent: 'center',
    },

    box: {
      // width: '103@s',
      height: '50@s',
      alignItems: 'center',
      // justifyContent: 'center',
      backgroundColor: '#EBEEF0',
      flexDirection: 'row',
    },
    text2: {
      color: '#03A0E3',
      fontSize: '12@s',
      fontWeight: ' 600',
      fontFamily: 'Nunito-Regular',
      height: '16@s',
      width: '97@s',
      marginTop: 1,
      marginLeft: 35,
      // alignItems: 'center',
      // justifyContent: 'center',
    },
    text22: {
      color: '#758DAC',
      fontSize: '12@s',
      fontWeight: ' 600',
      fontFamily: 'Nunito-Regular',
      height: '16@s',
      width: '100%',
      marginTop: 1,
      marginLeft: 15,
      flex: 1,
      // alignItems: 'center',
      // justifyContent: 'center',
    },
    text23: {
      color: '#758DAC',
      fontSize: '12@s',
      fontWeight: ' 600',
      fontFamily: 'Nunito-Regular',
      height: '16@s',
      width: '30@s',
      // marginTop: 1,
      marginLeft: 6,
      // alignItems: 'center',
      // justifyContent: 'center',
    },
    text24: {
      color: '#758DAC',
      fontSize: '12@s',
      fontWeight: ' 600',
      fontFamily: 'Nunito-Regular',
      height: '16@s',
      width: '100%',
      // marginTop: 1,
      marginLeft: 6,
      // alignItems: 'center',
      // justifyContent: 'center',
    },
    text3: {
      color: '#FB595D',
      fontSize: '12@s',
      fontWeight: ' 700',
      fontFamily: 'Nunito-Regular',
      height: '16@s',
      width: '100%',
      marginTop: 20,
      marginRight: 30,
      // marginLeft: 30,
      // alignItems: 'center',
      // justifyContent: 'center',
    },
    text33: {
      color: '#FB595D',
      fontSize: '12@s',
      fontWeight: ' 700',
      fontFamily: 'Nunito-Regular',
      height: '16@s',
      width: '100%',
      marginTop: 20,
      marginRight: 30,
      // marginLeft: 30,
      // alignItems: 'center',
      // justifyContent: 'center',
    },
    box1: {
      width: '103@s',
      height: '50@s',
      alignItems: 'center',
      // justifyContent: 'center',
      backgroundColor: '#EBEEF0',
      flexDirection: 'row',
    },
    // text2: {
    //   color: '#03A0E3',
    //   fontSize: '16@s',
    //   fontWeight: '700',
    //   fontFamily: 'Nunito-Regular',
    // },
    smallContainer: {
      position: 'absolute',
      justifyContent: 'space-between',
      // marginLeft: 10,
      // right: 60,
      // marginTop: 14,
      width: '60@s',
      height: '28@s',
    },
    icon: {
      width: '16@s',
      height: 13.71,
      marginLeft: '16@s',
      // marginTop: '6@s',
    },
    icon2: {
      width: '16@s',
      height: 13.71,
      marginLeft: '20@s',
      // marginTop: '6@s',
    },
    icon3: {
      width: '16@s',
      height: 13.71,
      marginLeft: '20@s',
      // marginTop: '6@s',
    },
    icon4: {
      width: '16@s',
      height: 13.71,
      marginLeft: '98@s',
      // marginTop: '6@s',
      flex: 2,
    },
    icon5: {
      width: '16@s',
      height: 13.71,
      marginLeft: '30@s',
      marginTop: '40@s',
    },
    smallContainer1: {
      position: 'absolute',
      justifyContent: 'space-between',
      // marginLeft: 10,
      // right: 60,
      // marginTop: 14,
      width: '60@s',
      height: '28@s',
    },
    coinContainer222: {
      width: '100%',
      height: '28@ms',
      borderRadius: 50,
      justifyContent: 'space-around',
      alignItems: 'center',
      paddingHorizontal: '12@ms',
      flexDirection: 'row',
      backgroundColor: '#EBEEF0',
    },
    coinContainer223: {
      width: '100%',
      height: '28@ms',
      borderRadius: 50,
      justifyContent: 'space-around',
      alignItems: 'center',
      paddingHorizontal: '12@ms',
      flexDirection: 'row',
      backgroundColor: '#EBEEF0',
    },
    coinImage: {
      alignItems: 'center',
      justifyContent: 'center',
      height: '18@ms',
      width: '18@ms',
      marginTop: 2,
    },
    coinText: {
      fontFamily: 'Nunito-Regular',
      fontSize: '14@s',
      fontWeight: '600',
      color: '#758DAC',
      marginTop: 2,
      // marginLeft: 5,
    },
    smallText: {
      fontFamily: 'Nunito-Regular',
      fontSize: '12@s',
      fontWeight: '600',
      color: '#84BD47',
      // marginTop: 6,
      height: '16@s',
      width: '100%',
    },
    smallText1: {
      fontFamily: 'Nunito-Regular',
      fontSize: '14@s',
      fontWeight: '600',
      color: '#323A3D',
      marginTop: 20,
      marginLeft: 20,
      height: '19@s',
      width: '58@s',
    },
    smallText11: {
      fontFamily: 'Nunito-Regular',
      fontSize: '14@s',
      fontWeight: '600',
      color: '#323A3D',
      marginTop: 20,
      marginLeft: 102,
      height: '19@s',
      width: '100%',
    },
    coinContainer1: {
      alignContent: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      height: '40@s',
      marginTop: '25@s',
    },
    popup: {
      width: 214,
      height: 212,
      borderRadius: 14,
      backgroundColor: '#EBEEF0',
      paddingHorizontal: 10,
      position: 'absolute',
      top: 145,
      right: 51,
      shadowColor: '#FDFDFD',
      shadowOpacity: 1,
      shadowOffset: { width: 6, height: 10 },
      textShadowRadius: 6,
      elevation: 3,
    },
    popup2: {
      width: 214,
      height: 137,
      borderRadius: 14,
      backgroundColor: '#EBEEF0',
      paddingHorizontal: 10,
      position: 'absolute',
      marginTop: '400@s',
      right: 51,
      shadowColor: '#FDFDFD',
      shadowOpacity: 1,
      shadowOffset: { width: 6, height: 10 },
      textShadowRadius: 6,
      elevation: 3,
    },
    popup3: {
      width: 214,
      height: 137,
      borderRadius: 14,
      backgroundColor: '#EBEEF0',
      paddingHorizontal: 10,
      position: 'absolute',
      marginTop: '400@s',
      right: 51,
      shadowColor: '#FDFDFD',
      shadowOpacity: 1,
      shadowOffset: { width: 6, height: 10 },
      textShadowRadius: 6,
      elevation: 3,
    },
    popup4: {
      width: 214,
      height: 137,
      borderRadius: 14,
      backgroundColor: '#EBEEF0',
      paddingHorizontal: 10,
      position: 'absolute',
      marginTop: '500@s',
      right: 51,
      shadowColor: '#FDFDFD',
      shadowOpacity: 1,
      shadowOffset: { width: 6, height: 10 },
      textShadowRadius: 6,
      elevation: 3,
    },
    option: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItem: 'center',
      paddingVertical: 7,
      borderBottomColor: '#ccc',
    },
    option2: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItem: 'center',
      paddingVertical: 7,
      borderBottomColor: '#ccc',
    },
    option3: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItem: 'center',
      paddingVertical: 7,
      borderBottomColor: '#ccc',
    },
    option4: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItem: 'center',
      paddingVertical: 7,
      borderBottomColor: '#ccc',
    },
  });

export default styles;
