import { Dimensions } from 'react-native';
import { s, ScaledSheet } from 'react-native-size-matters';

const width =
  Dimensions.get('window').width >= Dimensions.get('window').height
    ? Dimensions.get('window').height
    : Dimensions.get('window').width;

const styles = (direction: string) =>
  ScaledSheet.create({
    container: {
      width: '100%',
      height: '100%',
      backgroundColor: '#EBEEF0',
      zIndex: -10,
    },
    safeAreaView: { alignSelf: 'stretch' },
    gradientTextContainer: {
      width: '126@s',
      justifyContent: 'center',
      alignItems: 'center',
      height: '22@s',
    },
    gradientTextStyle: {
      fontSize: '16@s',
      fontFamily: 'Nunito-Regular',
      fontWeight: '700',
      textAlign: 'center',
    },
    topContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      marginLeft: '12@s',
      marginTop: '7.9@s',
    },
    topContainer2: {
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      marginTop: '19@s',

      right: '22@s',
    },
    container2: {
      marginTop: 8,
      width: '100%',
      height: '100%',
      marginBottom: '40@s',
    },

    rightComponent: {
      flexDirection: direction === 'rtl' ? 'row-reverse' : 'row',
      left: direction === 'rtl' ? '20@s' : undefined,
      right: direction === 'rtl' ? undefined : '20@s',
      position: 'absolute',
    },

    buttonRow: {
      flexDirection: 'row',
      marginTop: '14.32@s',
      width: '292@s',
      height: '40@s',
      alignSelf: 'center',
    },
    button8: {
      marginLeft: '19@s',
    },
    buttonRow2: {
      width: '154@s',
      height: '25@s',
      alignSelf: 'flex-end',
      right: '42.36@s',
      justifyContent: 'space-between',
      flexDirection: 'row',
    },
    review: {
      marginTop: '14.32@s',
      marginHorizontal: '20@s',
      backgroundColor: '#EBEEF0',
    },

    profileImgContainer1: {
      marginTop: '65@s',
      justifyContent: 'center',
      alignItems: 'center',
    },
    childImage: {
      marginTop: '22.71@s',
      justifyContent: 'center',
      alignItems: 'center',
    },
    childImage1: {
      marginTop: '22.59@s',
      justifyContent: 'center',
      alignItems: 'center',
    },
    pointsImage: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    readingImage: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    coinImage: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    silverImage: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    finishImgContainer1: {
      marginTop: '37@s',
      justifyContent: 'center',
      alignItems: 'center',
    },
    profileImg1: {
      height: '154@s',
      width: '144@s',
    },
    childImg1: {
      height: '31.59@s',
      width: '31.59@s',
    },
    childImg2: {
      height: '63.72@s',
      width: '63.72@s',
    },
    pointsImg2: {
      height: '26.24@s',
      width: '26.24@s',
    },
    silverImg2: {
      height: '26.24@s',
      width: '26.24@s',
    },
    coinImg2: {
      height: '26.24@s',
      width: '26.24@s',
    },
    readingImg2: {
      height: '26.24@s',
      width: '26.24@s',
    },
    profileImg2: {
      height: '126.13@s',
      width: '154@s',
    },
    loveImg: {
      height: '23@s',
      width: '23@s',
    },
    playImg2: {
      height: '50@s',
      width: '34.28@s',
      resizeMode: 'contain',
      position: 'absolute',
      marginLeft: '93@s',
      marginTop: '20@s',
    },
    reviewContainer2: {
      height: '106@s',
      paddingHorizontal: '15.87@s',
      backgroundColor: '#EBEEF0',
    },
    avrgRatings: {
      position: 'absolute',
      top: '7.55@s',
      right: '10.74@s',
      alignItems: 'center',
    },
    button2: {
      height: '40@s',
      width: '136@s',
      backgroundColor: '#EBEEF0',
    },

    button: {
      height: '40@s',
      width: '136@s',
      backgroundColor: '#EBEEF0',
    },

    paginationContainer: {
      position: 'absolute',
      marginTop: '145@s',
      alignSelf: 'center',
    },
    paginationContainer3: {
      position: 'absolute',
      marginTop: '120@s',
      alignSelf: 'center',
    },
    paginationDots: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    dot: {
      width: '24@s',
      height: '16@s',
      marginHorizontal: 4,
    },
    dot3: {
      width: '24@s',
      height: '16@s',
      marginHorizontal: 4,
    },
    button4: {
      height: '23@s',
      width: '93@s',
    },
    continueContainer: {
      height: '15@s',
      width: '193@s',
      marginTop: '30.87@s',
      marginLeft: '32@s',
    },

    ButtonText: {
      color: '#EC4D61',
      fontSize: '12@s',
      fontWeight: '700',
      fontFamily: 'Nunito-Regular',
      height: '17@s',
      width: '70@s',
      marginTop: '11.1@s',
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: '32.06@s',
    },

    ButtonText5: {
      fontSize: '8.7@s',
      color: '#03A0E3',
      fontWeight: '700',
      fontFamily: 'Nunito-Regular',
      textAlign: 'center',
      width: '100%',
      height: '100%',
    },
    ButtonText1: {
      color: '#EC4D61',
      fontSize: '12@s',
      fontWeight: '700',
      fontFamily: 'Nunito-Regular',
      height: '17@s',
      width: '70@s',
      marginTop: '11.1@s',
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: '32.06@s',
    },
    finishBookText: {
      color: '#3B4568',
      fontSize: '11@s',
      fontWeight: '800',
      fontFamily: 'Nunito-Regular',
      alignSelf: 'center',
      textAlign: 'justify',
    },
    continueText: {
      color: '#3B4568',
      fontSize: '18.72@s',
      fontWeight: '800',
      fontFamily: 'Nunito-Regular',
      height: '26@s',
      width: '123@s',
      alignItems: 'center',
      justifyContent: 'center',
    },
    modelText: {
      color: '#455157',
      fontSize: '10.5@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      marginLeft: '6.37@s',
      width: '75.72@s',
      // backgroundColor: 'red',
    },
    modelText3: {
      color: '#3B4568',
      fontSize: '9@s',
      fontWeight: '800',
      fontFamily: 'Nunito-Regular',
      marginLeft: '27.67@s',
      marginTop: '18.74@s',
      // width: '75.72@s',
      // backgroundColor: 'red',
    },
    modelText2: {
      color: '#455157',
      fontSize: '10.49@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      marginLeft: '16.49@s',
    },
    flatlist: {
      paddingHorizontal: '18@s',
      justifyContent: 'center',
    },
    flatlist1: {
      width: '217@s',
      height: '51@s',
      backgroundColor: '#EBEEF0',
      left: '34@s',
      top: '15.4@s',
      borderRadius: 5.25,
      alignItems: 'center',
      justifyContent: 'center',
    },
    regularButton1: {
      width: '30@s',
      height: '30@s',
      position: 'absolute',
      left: '8@s',
    },
    regularButton2: {
      width: '30@s',
      height: '30@s',
      position: 'absolute',
      top: '70@s',
      right: '21@s',
    },
    regularButton11: {
      width: '21.18@s',
      height: '21.18@s',
      position: 'absolute',
      // backgroundColor: 'red',
      alignSelf: 'flex-start',
      left: '-16@s',
    },
    regularButton22: {
      width: '21.18@s',
      height: '21.18@s',
      position: 'absolute',
      // backgroundColor: 'blue',
      alignSelf: 'flex-end',
      right: '-15@s',
    },
    reviewText: {
      color: '#3B4568',
      fontSize: '18.72@s',
      fontWeight: '800',
      fontFamily: 'Nunito-Regular',
      height: '26@s',
      width: '117@s',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: '23.79@s',
      marginLeft: '32@s',
    },
    moreText: {
      color: '#3B4568',
      fontSize: '18.72@s',
      fontWeight: '800',
      fontFamily: 'Nunito-Regular',
      marginTop: '23.79@s',
      marginLeft: '32@s',
    },
    videoText: {
      color: '#2F4868',
      fontSize: '9@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      marginTop: '56.79@s',
      marginLeft: '11.62@s',
    },
    videoText2: {
      color: '#03A0E3',
      fontSize: '6.19@s',
      fontWeight: '700',
      fontFamily: 'Nunito-Regular',
      height: '26@s',
      width: '117@s',
      marginLeft: '11.62@s',
    },
    reviewText3: {
      color: '#000000',
      fontSize: '13.08@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',

      marginTop: '11.9@s',
      marginBottom: '5.99@s',
    },
    rateReviewText: {
      color: '#3B4568',
      fontSize: '16.13@s',
      fontWeight: '800',
      fontFamily: 'Nunito-Regular',
      alignItems: 'center',
      justifyContent: 'center',
      top: '11.9@s',
    },
    rateReviewText1: {
      color: '#758DAC',
      fontSize: '13.44@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      alignItems: 'center',
      justifyContent: 'center',
      top: '11.9@s',
    },
    reviewText4: {
      color: '#758DAC',
      fontSize: '11@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
    },
    reviewText5: {
      color: '#84BD47',
      fontSize: '11@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      left: '7@s',
    },
    reviewText6: {
      color: '#03A0E3',
      fontSize: '13.08@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      width: '74.17@s',
      height: '18.18@s',
    },
    reviewText7: {
      color: '#000000',
      fontSize: '9.7@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      alignItems: 'center',
      justifyContent: 'center',
    },
    reviewText8: {
      color: '#03A0E3',
      fontSize: '21.08@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: '3@s',
    },
    reviewText9: {
      color: '#FFFFFF',
      fontSize: '8.9@s',
      fontWeight: '800',
      fontFamily: 'Nunito-Regular',
      alignItems: 'center',
    },
    reviewRow: {
      flexDirection: 'row',
    },
    neomorphMargin: { marginRight: '20@ms' },
    neomorphContainer: {
      marginTop: '20@ms',
      height: '139@s',
    },
    neomorphMargin1: { marginRight: '20@ms' },
    neomorphContainer1: {
      alignSelf: 'center',
    },
    card: {
      height: '139@s',
      width: '125@ms',
      backgroundColor: '#EBEEF0',
    },
    card1: {
      height: '36@s',
      width: '100%',
      marginLeft: '11.16@s',
    },
    cardImage: {
      height: '139@s',
      width: '100%',
    },
    cardImage2: {
      paddingHorizontal: '12@s',
      height: '36@s',
      width: '36@s',
    },

    starRatingTop: {
      flexDirection: 'row',
    },
    buttonNeumorph: {
      width: '77.07@s',
      height: '23.21@s',
      marginTop: '7.35@s',
    },
    loadButton: {
      width: '77.07@s',
      height: '23.21@s',
      alignItems: 'center',
      justifyContent: 'center',
    },
    neomorphContainer2: {
      paddingHorizontal: '20@s',
      marginBottom: '20@s',
      marginTop: '19.72@s',
    },
    container5: {
      backgroundColor: '#EBEEF0',
      width: '100%',
      height: '156@ms',
      borderRadius: 14,
    },
    rating: {
      width: '100%',
      height: '48@s',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#EBEEF0',
      marginTop: '12.18@s',
    },
    container6: {
      paddingHorizontal: '15@s',
      paddingVertical: '15@s',
    },
    typeContainer: {
      width: '100%',
      height: '51@s',
      marginHorizontal: '20@s',
      fontSize: '14@s',
    },
    container7: {
      flexDirection: 'row',
      marginBottom: '3.26@s',
    },
    text5: {
      color: '#2F4868',
      fontSize: '18@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      height: '25@s',
      width: '99@s',
      flex: 1,
    },
    text6: {
      color: '#03A0E3',
      fontSize: '12@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      height: '16@s',
      width: '76@s',
    },
    imageStyle1: {
      width: '16.5@s',
      height: '22@s',
      marginLeft: '22@s',
    },
    imageStyle4: {
      width: '16.5@s',
      height: '22@s',
      marginLeft: '22@s',
      tintColor: 'red',
    },
    text7: {
      flex: 1,
      color: '#758DAC',
      fontSize: '15@s',
      fontWeight: '600',
      fontFamily: 'Nunito-Regular',
      height: '72@s',
      width: '207@s',
      marginTop: '12.26@s',
    },

    imageStyle2: {
      justifyContent: 'center',
      resizeMode: 'contain',
      width: '90@s',
      height: '90@s',
      position: 'absolute',
    },
    imageStyle3: {
      resizeMode: 'contain',
      width: '30@s',
      height: '30@s',
      marginTop: '10@s',
      marginLeft: '10@s',
    },
    imageContainer4: {
      alignItems: 'center',
      justifyContent: 'center',
      width: '78@s',
      height: '78@s',
    },
    neomorphContainer3: {
      marginBottom: '7@s',
      paddingHorizontal: '34@s',
    },

    slidingContainer: {
      marginTop: '12@s',
      width: '100%',
      marginBottom: '23@s',
    },
    slidingContainer2: {
      marginTop: '12@s',
      marginBottom: '20@s',
    },
    slidingContainer3: {
      marginTop: '16@s',
      height: '140@s',
    },
    badges: {
      width: '128@s',
      height: '155@s',
      marginLeft: '31@s',
    },
    badges2: {
      width: '95@s',
      height: '97@s',
      position: 'absolute',
      left: '62.19@s',
      borderRadius: '9.26@s',
    },
    videoContainer: {
      width: '111@s',
      height: '84@s',
      backgroundColor: '#E5E5E5',
      borderRadius: 5.2,
      elevation: 3,
      shadowColor: '#939393',
      left: '54@s',
      marginTop: '50@s',
    },
    modalContainer: {
      // flex: 1,
      // borderWidth: 2,
      height: '100%',
      alignItems: 'center',
      backgroundColor: ' rgba(0, 0, 0, 0.71)',
    },
    modalRow: {
      flexDirection: 'row',
      marginTop: '26.24@s',
      marginLeft: '26.3@s',
      alignItems: 'center',
    },
    modalRow1: {
      flexDirection: 'row',
      marginTop: '8.25@s',
      marginLeft: '26.3@s',
      alignItems: 'center',
    },
    modalRow2: {
      flexDirection: 'row',
      marginTop: '8.25@s',
      marginLeft: '26.3@s',
      alignItems: 'center',
    },
    modalRow3: {
      flexDirection: 'row',
      marginTop: '8.25@s',
      marginLeft: '26.3@s',
      alignItems: 'center',
    },
    modalView: {
      borderColor: 'white',
      borderRadius: '15@s',
      backgroundColor: '#F9F9F9',
      height: '364.14@s',
      width: '284@s',
      marginTop: '60@s',
    },
  });

export default styles;
