import { Dimensions, StyleSheet } from 'react-native';

const width =
  Dimensions.get('window').width >= Dimensions.get('window').height
    ? Dimensions.get('window').height
    : Dimensions.get('window').width;

const styles = (direction: string) =>
  StyleSheet.create({
    container: {
      width: '100%',
      height: '100%',
      backgroundColor: '#E5E5E5',
    },
    container1: {
      // paddingHorizontal: 30,
      // marginTop: 2,
      width: '100%',
      height: '40%',
      backgroundColor: '758DAC',
      paddingBottom: 25,
    },
    container2: {
      // paddingHorizontal: 30,
      left: 20,
      width: '91.9%',
      height: '50%',
      backgroundColor: '758DAC',
      paddingBottom: 25,
      justifyContent: 'center',
      alignItems: 'center',
    },
    safeAreaView: { alignSelf: 'stretch' },
    labelTextContainer: {
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
      alignSelf: 'flex-end',
      marginBottom: 20,
      width: width - 60,
    },
    rightComponent: {
      flexDirection: direction === 'rtl' ? 'row-reverse' : 'row',
      left: direction === 'rtl' ? 20 : undefined,
      right: direction === 'rtl' ? undefined : 20,
      position: 'absolute',
    },
    neomorphContainer: {
      marginTop: 52,
      justifyContent: 'center',
      alignItems: 'center',
    },
    inputContainer: {
      width: width - 60,
      height: 50,
      borderRadius: 50,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#EBEEF0',
    },
    insidetext: {
      color: '#03A0E3',
      fontWeight: '600',
      fontSize: 16,
      fontFamily: 'Nunito',
      left: 65,
      marginTop: -75,
      // letterSpacing: 0.75,
      lineHeight: 18,
      alignSelf: 'auto',
    },
    saveButton: {
      color: '#03A0E3',
      fontSize: 12,
      fontWeight: '700',
      backgroundColor: 'transparent',
      fontFamily: 'Nunito-Regular',
    },
    topContainer: {
      width: 38,
      height: 10,
      left: 20,
      radius: 50,
      bottom: 2,
      // flexDirection: 'row',
      // justifyContent: 'flex-start',
      // alignItems: 'center',
      // top: 40,
      // marginBottom: 27,
    },
    rectangle: {
      borderBottomWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderColor: '#FDFDFD',
      width: '100%',
      height: 110,
      backgroundColor: '#EBEEF0',
      elevation: 20,
      // paddingRight: 10,
      // marginTop: -2,
      // marginStart: ,
      borderBottomEndRadius: 25,
      borderBottomLeftRadius: 25,
      justifyContent: 'center',
    },
    stats: {
      width: '100%',
      height: 38,
      left: 150,
      right: 150,
      // top: 50,
      fontSize: 16,
      // justifyContent: 'center',
      fontFamily: 'Nunito',
      fontStyle: 'normal',
      fontWeight: '700',
    },
    rectangle2: {
      width: '100%',
      height: 230,
      borderWidth: 1,
      borderColor: '#FDFDFD',
      // left: -20,
      top: 10,
      borderRadius: 15,
      backgroundColor: '#EBEEF0',
      elevation: 10,
      // shadowColor: '#EBEEF0',
      justifyContent: 'center',
      alignItems: 'center',
    },
    rectangle3: {
      width: '100%',
      height: 120,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#FDFDFD',
      // shadowRadius: 14,
      marginTop: 31,
      // justifyContent: 'center',
      backgroundColor: '#EBEEF0',
      elevation: 10,
    },
    rectangle4: {
      width: '100%',
      height: 120,
      borderWidth: 1,
      borderColor: '#FDFDFD',
      borderRadius: 14,
      marginTop: 20,
      backgroundColor: '#EBEEF0',
      elevation: 10,
      // left: 20,
      // shadowRadius: 14,
      // justifyContent: 'center',
    },
    image: {
      width: '80%',
      // height: '80%',
      // width: 292.73,
      height: 140.48,
      // left: 30,
      top: 140,
      alignSelf: 'auto',
    },
    image1: {
      width: '80%',
      // height: '80%',
      // width: 292.73,
      height: 140.48,
      // left: 30,
      // bottom: 1,
    },
    image2: {
      width: '80%',
      // width: 292.73,
      height: 140.48,
      // height: '70%',
      top: -140,
    },
    Toptext: {
      // marginLeft: 120,
      // marginTop: 50,
      // marginLeft: 120,
      fontSize: 14,
      color: '#03A0E3',
      fontWeight: '600',
      fontFamily: 'Nunito',
      lineHeight: 19,
      backgroundColors: ['03A0E3', '#0D93CD'],
      textAlign: 'center',
    },
    text2: {
      fontSize: 10,
      color: '#03A0E3',
      fontWeight: '600',
      fontFamily: 'Nunito',
      lineHeight: 22,
    },
    text: {
      marginLeft: 120,
      marginTop: 50,
      fontSize: 14,
      color: '#323A3D',
      fontWeight: '600',
      fontFamily: 'Nunito',
      lineHeight: 19,
      textAlign: 'center',
    },
    elipse1: {
      width: 89.27,
      height: 89.27,
      left: 20,
      marginTop: -50,
      // marginVertical: -24,
      marginHorizontal: 10,
      resizeMode: 'contain',
      // height: width / 2,
      // width: width / 5,
    },
    elipse2: {
      width: 83.27,
      height: 89.27,
      left: 36,
      marginTop: -75,
      // marginVertical: -24,
      resizeMode: 'contain',
      // height: width / 2,
      // width: width / 5,
    },
    elipse3: {
      width: 83.27,
      height: 89.27,
      left: 38,
      marginTop: -81,
      // marginVertical: -24,
      resizeMode: 'contain',
      // height: width / 2,
      // width: width / 5,
    },
    elipse4: {
      width: 83.27,
      height: 89.27,
      left: 38,
      marginTop: -90,
      // marginVertical: -24,
      resizeMode: 'contain',
    },
    box: {
      width: '20%',
      height: 29,
      top: 125,
      // left: 130,
      right: 21,
      fontFamily: 'Nunito',
      borderRadius: 50,
      backgroundColor: '#EBEEF0',
      borderColor: '#FDFDFD',
      borderWidth: 1,
      elevation: 10,
      alignItems: 'center',
      alignSelf: 'flex-end',
    },
  });

export default styles;
