import { Dimensions } from 'react-native';
import { ms, scale, ScaledSheet } from 'react-native-size-matters';

const styles = (isLast: boolean) =>
  ScaledSheet.create({
    safeAreaView: {
      alignSelf: 'stretch',
    },
    container: {
      width: '100%',
      height: '100%',
    },
    topContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
    },
    titleBarContainer: { position: 'absolute', width: '100%' },
    logoImageStyle: {
      position: 'absolute',
      height: '74@s',
      resizeMode: 'contain',
    },
    homeTextStyle: {
      fontSize: '18.72@s',
      fontFamily: 'Nunito-Regular',
      fontWeight: '700',
      textAlign: 'center',
    },
    homeTextContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      height: '26@s',
    },
    iconContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      height: '44@s',
      width: '88@s',
    },
    searchContainer: {
      backgroundColor: '#EBEEF0',
      height: '44@s',
      width: '44@s',
      borderTopRightRadius: '50@s',
      borderBottomRightRadius: '50@s',
      alignItems: 'center',
      justifyContent: 'center',
    },
    menuContainer: {
      height: '44@s',
      width: '44@s',
      backgroundColor: '#EBEEF0',
      borderTopLeftRadius: '50@s',
      borderBottomLeftRadius: '50@s',
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconImageStyle: {
      width: '20@s',
      height: '20@s',
    },
    swiperContainer: {
      width: '100%',
      height: '570@s',
      marginTop: '74@s',
    },
    secondContainer: {
      width: '100%',
      height: '100%',
      marginTop: '-40@s',
      backgroundColor: '#EBEEF0',
      borderTopLeftRadius: '24@ms',
      borderTopRightRadius: '24@ms',
      marginBottom: '50@s',
    },
    paginationContainer: {
      justifyContent: 'center',
      bottom: '140@s',
    },
    paginationDots: {
      height: '16@s',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    activeDot: {
      width: '17.34@s',
      height: '17.34@s',
      borderRadius: '17.34@s',
      borderWidth: '2@s',
      marginHorizontal: 4,
      backgroundColor: '#FFFFFF',
      borderColor: '#03A0E3',
    },
    inActiveDot: {
      width: '17.34@s',
      height: '17.34@s',
      borderRadius: '17.34@s',
      borderWidth: '0.80@s',
      marginHorizontal: 4,
      backgroundColor: 'rgba(217, 217, 217, 0.5)',
      borderColor: '#FFFFFF',
    },
    mainContent: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    image: {
      resizeMode: 'stretch',
      height: '100%',
      width: '100%',
    },
    gradientTextContainer2: {
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      bottom: '150@s',
    },
    buttonContainer: {
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      bottom: '50@s',
      flexDirection: 'row',
    },
    gradientTextStyle2: {
      fontSize: '53@s',
      fontFamily: 'Nunito-Regular',
      fontWeight: '900',
      textAlign: 'center',
      color: '#FFFFFF',
    },
    subTitleTextStyle: {
      fontSize: '12.94@s',
      fontFamily: 'Nunito-Regular',
      fontWeight: '700',
      textAlign: 'center',
      color: '#FFFFFF',
      width: '90%',
    },
    playButtonStyle: {
      width: '125.84@s',
      height: '52@s',
      borderRadius: '5.2@s',
      backgroundColor: '#03A0E3',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
    },
    playHomeImage: {
      width: '35.68@s',
      height: '35.68@s',
      resizeMode: 'contain',
    },
    playButtonText: {
      fontFamily: 'Nunito-Regular',
      fontWeight: '700',
      fontSize: '20.88@s',
      color: '#FFFFFF',
      marginLeft: '15.91@ms',
    },
    moreInfoButtonStyle: {
      width: '187.2@s',
      height: '52@s',
      borderRadius: '5.2@s',
      backgroundColor: 'rgba(255, 255, 255, 0.3)',
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: '16.64@s',
    },
    moreInfoImage: {
      width: '39.68@s',
      height: '39.68@s',
      resizeMode: 'contain',
    },
    moreInfoButtonText: {
      fontFamily: 'Nunito-Regular',
      fontWeight: '700',
      fontSize: '20.88@s',
      color: '#FFFFFF',
      marginLeft: '15.91@s',
    },
    itemStyle: {
      marginTop: '26@s',
      marginLeft: '26@s',
      marginRight: isLast ? '26@s' : undefined,
      justifyContent: 'center',
      alignItems: 'center',
      height: '92.2@ms',
    },
    itemTextStyle: {
      marginTop: '15.6@s',
      fontFamily: 'Nunito-Regular',
      fontWeight: '600',
      fontSize: '14.56@s',
      textAlign: 'center',
      color: '#3B3B48',
      marginBottom: '10@s',
    },
    titleBox: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: '26@s',
      marginTop: '33.54@s',
      marginBottom: '10@s',
      alignItems: 'center',
    },
    gradientTextStyle: {
      fontSize: '17.93@s',
      fontFamily: 'Nunito-Regular',
      fontWeight: '800',
    },
    itemContinueReadingStyle: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: '10@ms',
    },
    continueReading: {
      height: '207@s',
      width: '164@s',
      borderRadius: '15.21@s',
      justifyContent: 'center',
      alignItems: 'center',
    },
    continueReadingImage: {
      height: '100%',
      width: '100%',
      resizeMode: 'contain',
      // borderRadius: '15.21@s',
    },
    continueReadingContent: {
      position: 'absolute',
      right: 0,
      backgroundColor: 'rgba(3, 160, 227, 0.15)',
      borderTopLeftRadius: '149.86@s',
      borderBottomLeftRadius: '149.86@s',
      width: '104.15@s',
      height: '49.45@s',
      justifyContent: 'center',
    },
    continueReadingPercentage: {
      fontFamily: 'Nunito-Regular',
      fontWeight: '600',
      fontSize: '17.23@s',
      color: '#FFFFFF',
      marginLeft: '10@s',
    },
    neomorphContainer: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    itemWhatsNewStyle: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: '11@s',
    },
    whatsNew: {
      height: '207.49@s',
      width: '164.74@s',
      borderRadius: '15.21@s',
      justifyContent: 'center',
      alignItems: 'center',
    },
    whatsNewImage: {
      height: '100%',
      width: '100%',
      resizeMode: 'contain',
      // borderRadius: '15.21@s',
    },
    itemFavoritesStyle: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: '11@s',
    },
    favorites: {
      height: '210.39@s',
      width: '162.57@s',
      borderRadius: '6.2@s',
      // justifyContent: 'center',
      // alignItems: 'center',
      backgroundColor: '#EBEEF0',
    },
    favoritesImage: {
      height: '157.02@s',
      width: '128.42@s',
      borderRadius: '8.17@s',
      resizeMode: 'contain',
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
    },
    starImage: {
      width: '19.13@s',
      height: '19.13@s',
      marginTop: '7.29@s',
      marginLeft: '19.13@s',
      marginBottom: '9.65@s',
    },
    favoritesContent: {
      position: 'absolute',
      right: 0,
      backgroundColor: 'rgba(3, 160, 227, 0.15)',
      borderTopLeftRadius: '116.74@s',
      borderBottomLeftRadius: '116.74@s',
      width: '81.14@s',
      height: '38.53@s',
      justifyContent: 'center',
      alignSelf: 'center',
    },
    favoritesBottomContent: {
      position: 'absolute',
      bottom: 0,
      width: '100%',
      justifyContent: 'center',
      alignSelf: 'center',
      paddingLeft: '17.61@s',
      marginBottom: '15.76@s',
    },
    favoritesPercentage: {
      fontFamily: 'Nunito-Regular',
      fontWeight: '600',
      fontSize: '11.45@s',
      color: '#FFFFFF',
      marginLeft: '10@s',
    },
    favoritesBottomTitle: {
      fontFamily: 'Nunito-Regular',
      fontWeight: '600',
      fontSize: '14@s',
      color: '#FFFFFF',
    },
    favoritesBottomSubTitle: {
      fontFamily: 'Nunito-Regular',
      fontWeight: '700',
      fontSize: '8.34@s',
      color: '#03A0E3',
    },
    neomorphMargin: { margin: '10@ms' },
    cardListStyle: {
      height: '110.4@s',
      width: Dimensions.get('window').width - scale(30),
      backgroundColor: '#EBEEF0',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    innerDirection: { flexDirection: 'row' },
    cardListImage: {
      height: '84.93@s',
      width: '69.64@s',
      borderRadius: '13@ms',
      margin: '12.74@ms',
    },
    cardBookImage: {
      height: '10.19@s',
      width: '10.19@s',
      marginLeft: '12.74@ms',
      resizeMode: 'contain',
    },
    cardContent: {
      width: '100%',
      flexDirection: 'column',
      paddingHorizontal: '11@s',
    },
    cardListContent: {
      flexDirection: 'column',
      height: '100%',
      paddingTop: '10@ms',
      alignItems: 'flex-start',
    },
    title: {
      fontFamily: 'Nunito-Regular',
      fontSize: '10.19@s',
      fontWeight: '700',
      color: '#2F4868',
    },
    author: {
      fontFamily: 'Nunito-Regular',
      fontSize: '6.8@s',
      fontWeight: '600',
      color: '#758DAC',
    },
    description: {
      fontFamily: 'Nunito-Regular',
      fontSize: '7.64@s',
      fontWeight: '800',
      color: '#3B4568',
    },
    descriptionContent: {
      fontFamily: 'Nunito-Regular',
      fontWeight: '600',
      fontSize: '6.79@s',
      letterSpacing: 0.005,
      color: '#758DAC',
      width: '35%',
      textAlign: 'justify',
    },
    authorName: {
      fontFamily: 'Nunito-Regular',
      fontSize: '6.8@s',
      fontWeight: '600',
      color: '#84BD47',
      marginBottom: 4,
    },
    priceListStyle: {
      fontFamily: 'Nunito-Regular',
      fontSize: '10.19@s',
      fontWeight: '700',
      color: '#03A0E3',
      right: ms(25),
      top: ms(11.89),
      position: 'absolute',
      width: '53@s',
      textAlign: 'right',
    },
    ratingPagesContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 6,
    },
    ratingCountStyle: {
      fontFamily: 'Nunito-Regular',
      fontWeight: '600',
      fontSize: '5.94@s',
      color: '#03A0E3',
      marginLeft: '4.91@s',
    },
    readMoreStyle: {
      fontFamily: 'Nunito-Regular',
      fontWeight: '600',
      fontSize: '6.79@s',
      letterSpacing: 0.005,
      color: '#03A0E3',
    },
    pageCountStyle: {
      fontFamily: 'Nunito-Regular',
      fontWeight: '600',
      fontSize: '5.94@s',
      color: '#3B4568',
      marginLeft: '5.52@s',
    },
    itemVideoToChildStyle: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: '11@s',
    },
    videoToChild: {
      height: '110@s',
      width: '110@s',
      borderRadius: '24@s',
      justifyContent: 'center',
      alignItems: 'center',
    },
    videoToChildImage: {
      height: '110@s',
      width: '110@s',
      resizeMode: 'stretch',
      // borderRadius: '24@s',
    },
    videoToChildPlayImage: {
      height: '46@s',
      width: '46@s',
      resizeMode: 'contain',
      // borderRadius: '24@s',
      alignSelf: 'center',
      position: 'absolute',
    },
    videoToChildTitle: {
      marginTop: 15,
      fontFamily: 'Nunito-Regular',
      fontWeight: '600',
      fontSize: '16@s',
      color: '#2F4868',
    },
    comingSoonTitle: {
      fontFamily: 'Nunito-Regular',
      fontWeight: '700',
      fontSize: '15@s',
      color: '#03A0E3',
      alignSelf: 'center',
    },
  });

export default styles;
